### ISSUE TITLE
Mysql connection 

### ISSUE THREAD

**Issue by ramyat1711** [soshace/elastic-search-example#1]
Hi,
I have trying to connect mysql server instead of postgres Database,getting below error,

message:"Client does not support authentication protocol requested by server; consider upgrading MySQL client"
name:"SequelizeConnectionError"

This is my configured database file,i just mentioned mysql database username and password,

database.js
module.exports = {
    database: {
        connectionString: 'mysql://localhost:3306',
        dbName: 'chocolateteddiesdb',
       
        options: {
            dialect: 'mysql',
            username   : 'root',
            password : 'password',
            pool: {
                max: 5,
                idle: 30000,
                acquire: 60000,
            }
        }
    },
    elasticSearch: {
        address: 'localhost:9200',
        log: 'info'
    }
};

please help me to resolve this...

**Comment by ramyat1711** [comment]
Hi,
The above mentioned issue has been fixed.

new issue has been occurred in elastic search

Elasticsearch ERROR: 2019-03-04T05:43:11Z
  Error: Request error, retrying
  HEAD http://localhost:9200/testdb_customers => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\log.js:225:56)
      at checkRespForFailure (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\transport.js:258:18)
      at HttpConnector.<anonymous> (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\connectors\http.js:157:7)
      at ClientRequest.bound (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\lodash\dist\lodash.js:729:21)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

Elasticsearch ERROR: 2019-03-04T05:43:11Z
  Error: Request error, retrying
  POST http://localhost:9200/testdb_customers/doc/2 => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\log.js:225:56)
      at checkRespForFailure (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\transport.js:258:18)
      at HttpConnector.<anonymous> (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\connectors\http.js:157:7)
      at ClientRequest.bound (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\lodash\dist\lodash.js:729:21)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

Elasticsearch WARNING: 2019-03-04T05:43:12Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2019-03-04T05:43:12Z
  No living connections

(node:2072) UnhandledPromiseRejectionWarning: Error: No Living connections
    at sendReqWithConnection (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\transport.js:225:15)
    at next (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\connection_pool.js:213:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:2072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Elasticsearch WARNING: 2019-03-04T05:43:12Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2019-03-04T05:43:12Z
  No living connections

(node:2072) UnhandledPromiseRejectionWarning: Error: No Living connections
    at sendReqWithConnection (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\transport.js:225:15)
    at next (E:\ramya\SampleReact\elastic-search\server\node_modules\sequelize-es-decorator\node_modules\elasticsearch\src\lib\connection_pool.js:213:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:2072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

please help me to solve it.
